version: "3.1"
services:
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  generator:
    build: ./generator
    container_name: generator
    restart: on-failure
    depends_on:
      - rabbitmq
  calculator:
    build: ./calculator
    container_name: calculator
    restart: on-failure
    depends_on:
      - rabbitmq
  storage:
    build: ./storage
    container_name: storage
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - ./results:/results
